### PR TITLE
Generate layouts using simulated annealing

### PR DESCRIPTION
**Pull request by hochshi**
I've copied and modified KeyboardAnalysis to create KeyboardSA which uses simulated annealing to optimize the total effort score.

Using this approach I've managed to generate the following layout:
```
1 2 3 4 5 6 7 8 9 0 - =
J C U M Q V F O , / [ ]
R S I T G B N E A L ;
Z W Y D K P H ' . X
```
With English books total scores:
`total * 	1.653	 0.025	 -0.003	 1.675`
and Linux source scores:
`total *:    2.248    0.106    0.005    2.359`

### CODE REVIEW

**Comment by stevep99** [comment]
Thanks  for submitting this, it looks like an interesting addition.
However I'm having trouble reviewing what has changed because the format of the existing code is changed. Could you edit to maintain the existing formatting?

**Comment by hochshi** [comment]
I think it should be fine now.
I must confess this code is super fast and dirty. The "right" way to do this would be for KeyboardSA to inherit from KeyboardAnalysis 😮‍💨 .

**Comment by stevep99** [comment]
Thanks, that looks better. So, I've played around with a bit, and ended up making some changes to tidy up some things:

- there is now only one entry point (the KeyboardAnalysis class), you can select simulated annealing mode with a new "--sa" switch. If you do that, it executes the code you have written.
- The classes for the standard annealing method and the SFB method looked so similar, the main difference as far as I can tell being the effort calculation. So I've removed them and just added an interface called EffortModel which lets you choose between them).
- There is a new object called SASettings with everything it needs to do the simulated annealing.

I also had to squash the formatting changes as I had an unpushed change I was having trouble merging with, hence this new PR.

I've done a quick run, but I haven't examined it in detail? Could you have a look and see if this code is still working as intended?

**Comment by stevep99** [comment]
See https://github.com/stevep99/keyboard-layout-analysis-tool/pull/3

**Pull request closed without merging**
